version: '3.4'
services:

  service:
    image: ghcr.io/paulushcgcj/database-evo:${DBEVO}
    restart: always
    ports:
      - "8080:8080"
    healthcheck:
      test: wget --spider -S http://127.0.0.1:8080/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"