server:
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: company
  main:
    lazy-initialization: false
    banner-mode: "off"
    allow-bean-definition-overriding: true
  jpa:
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        javax:
          cache:
            missing_cache_strategy: create
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.redisson.hibernate.RedissonRegionFactory
          redisson:
            fallback: true
            config: redisson.yaml
            entity:
              eviction:
                max_entries: 10000
              expiration:
                time_to_live: 600000
                max_idle_time: 300000
              localcache:
                max_idle_time: 300000
                time_to_live: 300000
                eviction_policy: LRU
                sync_strategy: INVALIDATE
                reconnection_strategy: CLEAR
                size: 5000
            collection:
              eviction:
                max_entries: 10000
              expiration:
                time_to_live: 600000
                max_idle_time: 300000
              localcache:
                max_idle_time: 300000
                time_to_live: 300000
                eviction_policy: LRU
                sync_strategy: INVALIDATE
                reconnection_strategy: CLEAR
                size: 5000
            naturalid:
              eviction:
                max_entries: 10000
              expiration:
                time_to_live: 600000
                max_idle_time: 300000
              localcache:
                max_idle_time: 300000
                time_to_live: 300000
                eviction_policy: LRU
                sync_strategy: INVALIDATE
                reconnection_strategy: CLEAR
                size: 5000
            query:
              eviction:
                max_entries: 10000
              expiration:
                time_to_live: 600000
                max_idle_time: 300000
              localcache:
                max_idle_time: 300000
                time_to_live: 300000
                eviction_policy: LRU
                sync_strategy: INVALIDATE
                reconnection_strategy: CLEAR
                size: 5000
            timestamps:
              eviction:
                max_entries: 10000
              expiration:
                time_to_live: 600000
                max_idle_time: 300000
              localcache:
                max_idle_time: 300000
                time_to_live: 300000
                eviction_policy: LRU
                sync_strategy: INVALIDATE
                reconnection_strategy: CLEAR
                size: 5000

  datasource:
    url: jdbc:postgresql://${io.github.paulushcgcj.database.host}/${io.github.paulushcgcj.database.name}
    username: ${io.github.paulushcgcj.database.username}
    password: ${io.github.paulushcgcj.database.password}
  flyway:
    locations: classpath:db/migration
    enabled: true
    validate-on-migrate: true
    user: ${io.github.paulushcgcj.database.username}
    password: ${io.github.paulushcgcj.database.password}
    url: jdbc:postgresql://${io.github.paulushcgcj.database.host}/${io.github.paulushcgcj.database.name}

springdoc:
  webjars:
    prefix: /v3
  api-docs:
    groups:
      enabled: true
  show-actuator: true