version: '3.4'

services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: simple
    volumes:
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "mysql", "-u", "root", "-proot", "-e", "SHOW databases;" ]
      interval: 5s
      timeout: 10s
      retries: 10
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"

  cache:
    image: redis:5-alpine
    restart: always
    ports:
      - 6379:6379
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"


volumes:
  pg_data: {}
